// Generated by CoffeeScript 1.6.1
(function() {
  var addWord, fontSize, init, map, removeUnused;

  $(function() {
    return init();
  });

  map = {
    a: 'lpha (Al fah)',
    b: 'ravo (Brah Voh)',
    c: 'harlie (Char Lee)',
    d: 'elta (Dell Tah)',
    e: 'cho (Eck Oh)',
    f: 'oxtrot (Foks Trot)',
    g: 'olf (Golf)',
    h: 'otel (Hoh Tell)',
    i: 'ndia (In Dee Ah)',
    j: 'uliett (Jew Lee Ett)',
    k: 'ilo (Key Loh)',
    l: 'ima (Lee Mah)',
    m: 'ike (Mike)',
    n: 'ovember (No Vem Ber)',
    o: 'scar (Oss Car)',
    p: 'apa (Pah Pah)',
    q: 'uebec (Keh Beck)',
    r: 'omeo (Row Me Oh)',
    s: 'ierra (See Air Ah)',
    t: 'ango (Tang Go)',
    u: 'niform (You Nee Form)',
    v: 'ictor (Vik Tah)',
    w: 'hiskey (Wiss Key)',
    x: ' Ray (Ecks Ray)',
    y: 'ankee (Yang Key)',
    z: 'ulu (Zoo Loo)'
  };

  fontSize = function(len) {
    switch (false) {
      case !(len < 5):
        return 100;
      case !(len < 10):
        return 90;
      case !(len < 15):
        return 85;
      case !(len < 20):
        return 80;
      case !(len < 25):
        return 75;
      case !(len < 30):
        return 70;
      default:
        return 50;
    }
  };

  addWord = function($container, i, letter) {
    var html, placeholder, word;
    placeholder = $container.find('.word-' + i);
    word = map[letter.toLowerCase()] != null ? '<span class="oversize">' + letter.toUpperCase() + '</span>' + map[letter.toLowerCase()] : '';
    html = '<div class="word word-' + i + '" data-letter="' + letter + '"><div class="undersize">' + (i + 1) + '</div>' + word + '</div>';
    if (placeholder.length > 0) {
      if (placeholder.attr('data-letter') !== letter) {
        placeholder.attr({
          'data-letter': letter
        });
        return placeholder.html(html);
      }
    } else {
      return $container.append(html);
    }
  };

  removeUnused = function($container, max) {
    var i, words, _i, _ref, _results;
    words = $container.find('.word');
    if (words.length > max) {
      _results = [];
      for (i = _i = max, _ref = words.length; max <= _ref ? _i <= _ref : _i >= _ref; i = max <= _ref ? ++_i : --_i) {
        _results.push($('.word-' + i).remove());
      }
      return _results;
    }
  };

  init = function() {
    var $letters, $words, txt;
    $letters = $('#letters');
    $words = $('#words');
    $letters.keyup(function(e) {
      var i, letter, newSize, txt, _i, _len, _ref;
      txt = $letters.val();
      newSize = fontSize(txt.length);
      $letters.css({
        fontSize: newSize + 'px',
        width: (txt.length + 1) + 'ch'
      });
      _ref = txt.split('');
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        letter = _ref[i];
        addWord($words, i, letter);
      }
      removeUnused($words, txt.length);
      return window.location.hash = txt;
    });
    txt = window.location.hash.replace('#', '');
    return $letters.val(txt).keyup();
  };

}).call(this);
